package com.tapi.service.security.agreementdetails;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.4
 * 2013-12-20T17:35:09.968+08:00
 * Generated source version: 2.4.4
 * 
 */
@WebService(targetNamespace = "http://service.tapi.com/security/agreementdetails", name = "AgreementDetailService")
@XmlSeeAlso({ObjectFactory.class})
public interface AgreementDetailService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryAgreementDetail", targetNamespace = "http://service.tapi.com/security/agreementdetails", className = "com.tapi.service.security.agreementdetails.QueryAgreementDetail")
    @WebMethod
    @ResponseWrapper(localName = "queryAgreementDetailResponse", targetNamespace = "http://service.tapi.com/security/agreementdetails", className = "com.tapi.service.security.agreementdetails.QueryAgreementDetailResponse")
    public com.tapi.service.security.agreementdetails.AgreementDetailResponse queryAgreementDetail(
        @WebParam(name = "request", targetNamespace = "")
        com.tapi.service.security.agreementdetails.AgreementDetailRequest request
    );
}
