
package com.tapi.tcs.vc.webservice.DoucmentTypeService.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.5
 * 2019-03-26T17:14:33.640+08:00
 * Generated source version: 2.4.5
 * 
 */
public final class ProductService_ProductServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("server.webservice.abutment.sinosoft.com", "ProductService");

    private ProductService_ProductServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ProductService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ProductService_Service ss = new ProductService_Service(wsdlURL, SERVICE_NAME);
        ProductService port = ss.getProductServiceImplPort();  
        
        {
        System.out.println("Invoking eSystemRequest...");
        java.lang.String _eSystemRequest_arg0 = "";
        java.lang.String _eSystemRequest__return = port.eSystemRequest(_eSystemRequest_arg0);
        System.out.println("eSystemRequest.result=" + _eSystemRequest__return);


        }

        System.exit(0);
    }

}
