
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.tapi.tcs.vc.webservice.DoucmentTypeService.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.5
 * 2019-03-26T17:14:33.650+08:00
 * Generated source version: 2.4.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "ProductService",
                      portName = "ProductServiceImplPort",
                      targetNamespace = "server.webservice.abutment.sinosoft.com",
                      wsdlLocation = "http://10.100.135.37:9000/cxfServices/productService?wsdl",
                      endpointInterface = "com.tapi.tcs.vc.webservice.DoucmentTypeService.client.ProductService")
                      
public class ProductServiceImpl implements ProductService {

    private static final Logger LOG = Logger.getLogger(ProductServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.tapi.tcs.vc.webservice.DoucmentTypeService.client.ProductService#eSystemRequest(java.lang.String  arg0 )*
     */
    public java.lang.String eSystemRequest(java.lang.String arg0) { 
        LOG.info("Executing operation eSystemRequest");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
