package com.tapi.tcs.vc.webservice.DoucmentTypeService.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.5
 * 2019-03-26T17:14:33.660+08:00
 * Generated source version: 2.4.5
 * 
 */
@WebServiceClient(name = "ProductService", 
                  wsdlLocation = "http://10.100.135.37:9000/cxfServices/productService?wsdl",
                  targetNamespace = "server.webservice.abutment.sinosoft.com") 
public class ProductService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("server.webservice.abutment.sinosoft.com", "ProductService");
    public final static QName ProductServiceImplPort = new QName("server.webservice.abutment.sinosoft.com", "ProductServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.100.135.37:9000/cxfServices/productService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProductService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.100.135.37:9000/cxfServices/productService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProductService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProductService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
  

    /**
     *
     * @return
     *     returns ProductService
     */
    @WebEndpoint(name = "ProductServiceImplPort")
    public ProductService getProductServiceImplPort() {
        return super.getPort(ProductServiceImplPort, ProductService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductService
     */
    @WebEndpoint(name = "ProductServiceImplPort")
    public ProductService getProductServiceImplPort(WebServiceFeature... features) {
        return super.getPort(ProductServiceImplPort, ProductService.class, features);
    }

}
