package com.tapi.service.security.userdetails;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.4
 * 2013-12-20T17:24:10.046+08:00
 * Generated source version: 2.4.4
 * 
 */
@WebService(targetNamespace = "http://service.tapi.com/security/userdetails", name = "UserDetailService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserDetailService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryUserDetail", targetNamespace = "http://service.tapi.com/security/userdetails", className = "com.tapi.service.security.userdetails.QueryUserDetail")
    @WebMethod
    @ResponseWrapper(localName = "queryUserDetailResponse", targetNamespace = "http://service.tapi.com/security/userdetails", className = "com.tapi.service.security.userdetails.QueryUserDetailResponse")
    public com.tapi.service.security.userdetails.UserDetailResponse queryUserDetail(
        @WebParam(name = "request", targetNamespace = "")
        com.tapi.service.security.userdetails.UserDetailRequest request
    );
}
