package com.tapi.service.security.agreementdetails1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.4
 * 2013-12-20T17:35:32.296+08:00
 * Generated source version: 2.4.4
 * 
 */
@WebService(targetNamespace = "http://service.tapi.com/security/agreementdetails1", name = "AgreementDtoService")
@XmlSeeAlso({ObjectFactory.class})
public interface AgreementDtoService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryAgreementDto", targetNamespace = "http://service.tapi.com/security/agreementdetails1", className = "com.tapi.service.security.agreementdetails1.QueryAgreementDto")
    @WebMethod
    @ResponseWrapper(localName = "queryAgreementDtoResponse", targetNamespace = "http://service.tapi.com/security/agreementdetails1", className = "com.tapi.service.security.agreementdetails1.QueryAgreementDtoResponse")
    public com.tapi.service.security.agreementdetails1.AgreementDtoResponse queryAgreementDto(
        @WebParam(name = "request", targetNamespace = "")
        com.tapi.service.security.agreementdetails1.AgreementDtoRequest request
    );
}
