
package com.tapi.tcs.vc.webservice.DoucmentTypeService.client;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.4.5
 * 2019-03-26T17:14:33.658+08:00
 * Generated source version: 2.4.5
 * 
 */
 
public class ProductService_ProductServiceImplPort_Server{

    protected ProductService_ProductServiceImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ProductServiceImpl();
        String address = "http://10.100.135.37:9000/cxfServices/productService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ProductService_ProductServiceImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
