package com.tapi.tcs.vc.webservice.DoucmentTypeService.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.5
 * 2019-03-26T17:14:33.655+08:00
 * Generated source version: 2.4.5
 * 
 */
@WebService(targetNamespace = "server.webservice.abutment.sinosoft.com", name = "ProductService")
@XmlSeeAlso({ObjectFactory.class})
public interface ProductService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "ESystemRequest", targetNamespace = "server.webservice.abutment.sinosoft.com", className = "com.tapi.tcs.vc.webservice.DoucmentTypeService.client.ESystemRequest")
    @WebMethod(operationName = "ESystemRequest")
    @ResponseWrapper(localName = "ESystemRequestResponse", targetNamespace = "server.webservice.abutment.sinosoft.com", className = "com.tapi.tcs.vc.webservice.DoucmentTypeService.client.ESystemRequestResponse")
    public java.lang.String eSystemRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
