/**
 * @preserve jquery.tianan.Component 1.0 beta1
 * $Date: 2013-02-19 $
 * $author: lianchao $
 * $Rev: 1.05 $
 */

(function($){$.fn.twiceValidator=function(options){if(typeof(options)=='string'){switch(options){case"isEmpty":return this.each(function(){if($(this).attr("successValue")!=''){return false;}else{return true;}});}}
var opts=$.extend({},$.fn.twiceValidator.defaults,options);return this.each(function(){var $this=$(this);var value='';$(this).attr("successValue",'');var o=$.meta?$.extend({},opts,$this.data()):opts;$this.css("background-color",o.firstBG);$this.keypress(function(event){var keyCode=event.keyCode?event.keyCode:event.which;if(keyCode=='13'){if(value==''){value=$(this).val();$(this).val('');$(this).css("background-color",o.lastBG);}else{if($(this).val()!=value){alert(o.alertMessage);value='';$(this).val('');$(this).css("background-color",o.firstBG);}else{value='';$(this).attr("successValue",$(this).val());$(this).css("background-color",o.successBG);}}}});$this.bind("paste",function(e){e.preventDefault();});$this.blur(function(){if(value==''){if($(this).val()!=$(this).attr("successValue")){if(''==$(this).val()){}}}else{if(''==$(this).val()){alert(o.secondAlertMessage);}}});});};$.fn.twiceValidator.value='';$.fn.twiceValidator.defaults={firstBG:'blue',lastBG:'yellow',successBG:'green',alertMessage:'两次输入值不一致，请确认!',firstAlertMessage:'请输入值!',secondAlertMessage:'请在重复输入处填值!'};})(jQuery);(function($){$.fn.dropDownList=function(options,val){if(typeof(options)=='string'){switch(options){case"disable":return this.each(function(){if(val){$(this).val(val);}
$(this).change();$(this).attr("disabled",true);});case"enable":return this.each(function(){$(this).attr("disabled",false);});case"selected":return this.each(function(){if(val){$(this).val(val);}
$(this).change();$(this).attr("selected",true);});}}
var opts=$.extend({},$.fn.dropDownList.defaults,options);return this.each(function(){var $this=$(this);var value='';var o=$.meta?$.extend({},opts,$this.data()):opts;if(o.trigger!=''){$(o.trigger).bind(o.event,function(){o.value=$(this).val();getData(o,$this);$($this).change();});o.value=$(o.trigger).val();getData(o,$this);$($this).change();}else{getData(o,$this);$($this).change();}});};$.fn.dropDownList.defaults={trigger:'',event:'',dataField:'',url:'',value:'',dataType:'json',data:'',selectedValue:''};$.fn.dropDownList.disable=function(value){return this.each(function(){if(value){$(this).val(value);}
$(this).change();$(this).attr("disabled",true);});};function getData(o,obj){if(o.data==''){getDataFromAjax(o,obj);}else{getDataFromLocal(o,obj);}}
function getDataFromLocal(o,obj){var options='<option value="">-请选择-</option>';if(o.selectedValue!=''){$.each(o.data,function(index,value){if(undefined!=value.name){if($(o.trigger).val()==value.name){var selected="";if(o.selectedValue==value.value){selected="selected=\"true\"";}
options+='<option value="'+value.value+'"'+selected+' >'+value.label+'</option>';}}else{var selected1="";if(o.selectedValue==value.value){selected1="selected=\"true\"";}
options+='<option value="'+value.value+'"'+selected1+' >'+value.label+'</option>';}});}else if(o.value!=''){$.each(o.data,function(index,value){if(value[o.dataField]==o.value){options+='<option value="'+value.value+'">'+value.label+'</option>';}});}else{$.each(o.data,function(index,value){options+='<option value="'+value.value+'">'+value.label+'</option>';});}
$(obj).html(options);}
function getDataFromAjax(o,obj){var data='';if(o.dataField!=''){data=o.dataField+"="+o.value;}
var options='<option value="">-请选择-</option>';$.get(o.url,data,function(data){$.each(data,function(index,value){if(undefined!=value.name){if($(o.trigger).val()==value.name){var selected="";if(o.selectedValue==value.value){selected="selected=\"true\"";}
options+='<option value="'+value.value+'"'+selected+' >'+value.label+'</option>';}}else{var selected1="";if(o.selectedValue==value.value){selected1="selected=\"true\"";}
options+='<option value="'+value.value+'"'+selected1+' >'+value.label+'</option>';}});$(obj).html(options);},o.dataType);}})(jQuery);(function($){$.fn.taAutoComplete=function(options,val){if(typeof(options)=='string'){switch(options){case"isValidate":return this.each(function(){var value=$(this).val();var validate=false;if($(this).val()!=''){$.each(o.source,function(){if(this.value==value){validate=true;}});if(!validate){alert(o.errorMsg);$(this).val('');}}});}}
var opts=$.extend({},$.fn.taAutoComplete.defaults,options);return this.each(function(){var $this=$(this);var o=$.meta?$.extend({},this.opts,$this.data()):opts;$.fn.taAutoComplete.source=o.source;if(typeof(o.source)=='string'){$(this).autocomplete({source:function(request,response){$.ajax({url:o.source,data:{codeCode:request.term},dataType:"json",success:function(data){response(data);}});},minLength:o.minLength,select:function(event,ui){$($this).val(ui.item.value);if(o.twoInput){var lableId=$($this).attr("id")+"Name";$("#"+$($this).attr("id")).change();$("#"+lableId).val(ui.item.lable);}
return false;},open:function(event,ui){if(o.height!=''){$($this).autocomplete("widget").css("height",o.height);$($this).autocomplete("widget").css("overflow-y","auto");}
if(o.width!=''){$($this).autocomplete("widget").css("width",o.width);$($this).autocomplete("widget").css("overflow-x","auto");}}}).data("autocomplete")._renderItem=function(ul,item){return $("<li style=\"width:200px;\"></li>").data("item.autocomplete",item).append("<a>"+item.value+"-"+item.lable+"</a>").appendTo(ul);};}else{$(this).autocomplete({source:o.source,minLength:o.minLength,select:function(event,ui){$($this).val(ui.item.value);if(o.twoInput){var lableId=$($this).attr("id")+"Name";$("#"+$($this).attr("id")).change();$("#"+lableId).val(ui.item.lable);}
return false;},open:function(event,ui){if(o.height!=''){$($this).autocomplete("widget").css("height",o.height);$($this).autocomplete("widget").css("overflow-y","auto");}
if(o.width!=''){$($this).autocomplete("widget").css("width",o.width);$($this).autocomplete("widget").css("overflow-x","auto");}}}).data("autocomplete")._renderItem=function(ul,item){return $("<li style=\"width:200px;\"></li>").data("item.autocomplete",item).append("<a>"+item.value+"-"+item.lable+"</a>").appendTo(ul);};}
if(o.twoInput){$($this).next().attr("tabindex","-1");}
$(this).dblclick(function(event){$(this).autocomplete("search");});$(this).keydown(function(event){var keyCode=event.keyCode?event.keyCode:event.which;switch(keyCode){case 9:case 19:case 13:case 27:case 33:case 34:case 35:case 36:case 37:case 38:case 39:case 40:case 45:case 46:case 91:case 93:case 112:case 113:case 114:case 115:case 116:case 117:case 118:case 119:case 120:case 121:case 122:case 123:case 192:break;default:$(this).next().val('');}});});}
$.fn.taAutoComplete.source='';$.fn.taAutoComplete.defaults={source:'',width:'',height:'',twoInput:true,errorMsg:'输入数据不合法，请重新输入'};})(jQuery);(function($){$.taBlockUI={message:"请求处理中，请稍候.",active:function(){$.blockUI({message:$.taBlockUI.message,showOverlay:true,css:{border:'none',padding:'15px',backgroundColor:'#000','-webkit-border-radius':'10px','-moz-border-radius':'10px',color:'#fff'},overlayCSS:{backgroundColor:'#b3b3b3'}})},inactive:function(){$.unblockUI();},setMessage:function(msg){$.taBlockUI.message=msg;}}})(jQuery);