package com.tapi.service.fin.visa.intf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.4
 * 2013-08-20T10:37:04.107+08:00
 * Generated source version: 2.4.4
 * 
 */
@WebService(targetNamespace = "http://service.tapi.com/fin/visa/intf", name = "VisaWebService")
@XmlSeeAlso({ObjectFactory.class, com.tapi.service.fin.common.dto.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface VisaWebService {

    @WebResult(name = "return", targetNamespace = "http://service.tapi.com/fin/visa/intf", partName = "return")
    @WebMethod
    public PrePayFeeActCancelCardResponse prePayFeeCancelActCard(
        @WebParam(partName = "arg0", name = "arg0")
        PrePayFeeCancelActCardRequest arg0
    );

    @WebResult(name = "return", targetNamespace = "http://service.tapi.com/fin/visa/intf", partName = "return")
    @WebMethod
    public RefundActCardResponse refundActCard(
        @WebParam(partName = "arg0", name = "arg0")
        RefundActCardRequest arg0
    );

    @WebResult(name = "return", targetNamespace = "http://service.tapi.com/fin/visa/intf", partName = "return")
    @WebMethod
    public PrePayFeeActCardResponse prePayFeeActCard(
        @WebParam(partName = "arg0", name = "arg0")
        PrePayFeeActCardRequest arg0
    );

    @WebResult(name = "return", targetNamespace = "http://service.tapi.com/fin/visa/intf", partName = "return")
    @WebMethod
    public VisaAccountToPaymentResponse visaAccountToPayment(
        @WebParam(partName = "arg0", name = "arg0")
        VisaAccountToPaymentRequest arg0
    );
}
