package com.tapi.service.security.userdetails1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.4
 * 2013-12-19T19:48:15.812+08:00
 * Generated source version: 2.4.4
 * 
 */
@WebService(targetNamespace = "http://service.tapi.com/security/userdetails1", name = "UserDtoService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserDtoService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryUserDto", targetNamespace = "http://service.tapi.com/security/userdetails1", className = "com.tapi.service.security.userdetails1.QueryUserDto")
    @WebMethod
    @ResponseWrapper(localName = "queryUserDtoResponse", targetNamespace = "http://service.tapi.com/security/userdetails1", className = "com.tapi.service.security.userdetails1.QueryUserDtoResponse")
    public com.tapi.service.security.userdetails1.UserDtoResponse queryUserDto(
        @WebParam(name = "request", targetNamespace = "")
        com.tapi.service.security.userdetails1.UserDtoRequest request
    );
}
