var statusValues={
	
	//申领单处理状态（0删除/l暂存/2等待发放/3发放暂存/4发放退回/5发放待确认）
	VC_APPLY_STATUS_APPLY_DELETE:"0",
	VC_APPLY_STATUS_APPLY_TEMPSAVE:"1",
	VC_APPLY_STATUS_APPLY_AWAITPROVIDE:"2",
	VC_APPLY_STATUS_PROVIDE_TEMPSAVE:"3",
	VC_APPLY_STATUS_PROVIDE_BACK:"4",
	VC_APPLY_STATUS_PROVIDE_AWAITCONFIRM:"5",
	
	//发放处理状态（0取消发放/1暂存/2待确认/3已确认/4确认退回）
	VC_PROVIDE_STATUS_PROVIDE_BACK:"0",
	VC_PROVIDE_STATUS_PROVIDE_TEMPSAVE:"1",
	VC_PROVIDE_STATUS_PROVIDE_AWAITCONFIRM:"2",
	VC_PROVIDE_STATUS_PROVIDE_CONFIRMED:"3",
	VC_PROVIDE_STATUS_PROVIDE_CONFIRMBACK:"4",
	
	//回收处理状态（0删除/1新建/2待审批/3审批退回/4审批通过）
	VC_RECYCLE_STATUS_DEL:"0",
	VC_RECYCLE_STATUS_TEMPSAVE:"1",
	VC_RECYCLE_STATUS_AWAITCONFIRM:"2",
	VC_RECYCLE_STATUS_CONFIRMBACK:"3",
	VC_RECYCLE_STATUS_CONFIRMED:"4"

}